/* ChiSQ Plot for multivariate normality testing */
%macro chisq_plot(dname,group);
proc iml;
   use &dname;
   read all var {&group} into x;
   close &dname;
   
   n = nrow(x);
   p = ncol(x);
   xbar = x[:,]`;
   s = (x`*x-n*xbar*xbar`)/(n-1);
   free di2 xi2;
   do i = 1 to n;
      di2 = di2//((x[i,]`-xbar)`*inv(s)*(x[i,]`-xbar));
      xi2 = xi2//cinv((i-.5)/n,p);
   end;
   maxx = int(max(xi2))+1;
   call symput('maxp',left(char(maxx)));  
   di2 = di2//maxx;
   call sort(di2,1);
   create result var {xi2 di2};
   append;
   close result;
quit;
data result;
   set result;
   dref = di2;
   run;
goptions reset=all;
goptions htitle=5 htext=3;
symbol1 value=dot color=blue w=2;
symbol2 value=none i=j color=red w=2;
axis1 order=(0 to &maxp) label=('Ordered Mahanobis Distance');
axis2 order=(0 to &maxp) label=(angle=90 'Chi square');
title1 'Plot of Squared Generalized Distance vs Chi-square Distribution';
proc gplot data=result;
   plot di2*xi2=1 di2*dref=2/overlay haxis=axis1 vaxis=axis2;
   run;
quit;
proc datasets lib=work;
   delete result;
   run;
quit;
%mend;
